- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5
